spring:
  config:
    activate:
      on-profile: local # Spring boot 2.4부터 spring.profiles 대체
  datasource:
    url: jdbc:h2:mem:testdb
    username: admin
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
logging:
  file:
    path: ../logs
file:
  upload:
    path: /Users/alxndr/Documents/file

