spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
#    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # CREATE : Application 실행 시점에 Table을 전부 지우고 재생성
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true  # System out
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true # false  / defualt = true

logging:
  level:
    org.hibernate.SQL: debug  # Logger
#    org.hibernate.type: trace # Show Query parameter